spring:
  application:
    name: ai-senior-java
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_rag_java
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/ai_rag_java
    user: postgres
    password: postgres

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ai_rag_java
    username: postgres
    password: postgres
  sql:
    init:
      mode: never

llm:
  openai:
    api:
      key: sk-xxxxx
    model: gpt-4o-mini
  ollama:
    base-url: http://localhost:11434
    model: llama3.2
    embedding-model: embeddinggemma
rag:
  embedding:
    dim: 768
